DB_USERNAME = "root"
DB_PASSWORD = ""
DB_HOST = "127.0.0.1" 
DB_PORT = "3306"
DB_NAME = "article"

SQLALCHEMY_DATABASE_URI = f"mysql+mysqlconnector://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False
